hide-cursor-when-typing = false

confirm-before-quit = false

[cursor]
shape = 'beam'
blinking = false
blinking-interval = 800

[editor]
program = "nano"
args = []

[window]
height = 650
mode = "windowed"
opacity = 0.8
blur = false
decorations = "enabled"

[renderer]
performance = "high"
backend = "automatic"
disable-unfocused-render = false
level = 1
filters = []

[fonts]
size = 16

[navigation]
mode = "bottomtab"
clickable = true
hide-if-single = false
use-current-path = false

[shell]
program = "/bin/fish"
args = ["--login"]

[colors]
background = "#282828"
foreground = "#eeeeee"
