hide-cursor-when-typing = false
confirm-before-quit = false

[cursor]
shape = 'beam'
blinking = false
blinking-interval = 800

[editor]
program = "nano"
args = []

[window]
height = 650
mode = "windowed"
opacity = 0.8
blur = false
decorations = "enabled"

[renderer]
performance = "low"
backend = "automatic"
disable-unfocused-render = false
level = 1
filters = []

[fonts]
size = 16

[navigation]
mode = "bookmark"
clickable = true
hide-if-single = false
use-current-path = false
use-split = true

[shell]
program = "/bin/fish"
args = ["--login"]

[colors]
background = "#282828"
foreground = "#eeeeee"

[bindings]
keys = [
    { key = "t", with = "control", action = "CreateTab" },
    # reset og bind
    { key = "t", with = "control | shift", action = "ReceiveChar" },
    { key = "w", with = "control", action = "CloseTab" },
    # override og bind
    { key = "w", with = "control | shift", action = "CloseUnfocusedTabs" },
    { key = "pageup", with = "control", action = "ReceiveChar" },
    { key = "pagedown", with = "control", action = "ReceiveChar" },
    { key = "pageup", with = "control", action = "SelectPrevTab" },
    { key = "pagedown", with = "control", action = "SelectNextTab" }
]
