live_config_reload = true

[shell]
program = "fish"

[colors.bright]
black = "0x4c4c4c"
blue = "0xb3deef"
cyan = "0x73cef4"
green = "0xc9d05c"
magenta = "0xff00ff"
red = "0xf43753"
white = "0xfeffff"
yellow = "0xffc24b"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x282828"
blue = "0xb3deef"
cyan = "0x73cef4"
green = "0xc9d05c"
magenta = "0xc605b3"
red = "0xf43753"
white = "0xeeeeee"
yellow = "0xffc24b"

[colors.primary]
background = "0x282828"
foreground = "0xeeeeee"

[cursor.style]
blinking = "Off"
shape = "Beam"

[debug]
render_timer = false

[font]
size = 12

[font.bold]
family = "mono"
style = "Bold"

[font.bold_italic]
family = "mono"
style = "Bold Italic"

[font.italic]
family = "mono"
style = "Italic"

[font.normal]
family = "mono"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[scrolling]
history = 100000

[window]
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 0
y = 0
