# all commands: https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs
theme = "jetbrains_dark"

[editor]
scrolloff = 1
mouse = true
bufferline = "always"
cursorline = true
cursorcolumn = true
rulers = [120]
true-color = true
auto-pairs = false      # do not automatically pair 
auto-completion = false # do not auto-complete; use 'completions' keymap (C-space) by default

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# https://docs.helix-editor.com/master/configuration.html#editorsoft-wrap-section
[editor.soft-wrap]
enable = false
wrap-indicator = "↩ "

[editor.indent-guides]
render = true
character = "▏"

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"
tab = "all"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-modification-indicator", "version-control", "file-name"]
right = [
  "position",
  "position-percentage",
  "total-line-numbers",
  "file-encoding",
  "file-line-ending",
]

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true
display-messages = true

[editor.file-picker]
hidden = false

[editor.search]
smart-case = true
wrap-around = true

[editor.smart-tab]
enable = false

[keys.normal]
# moving the view around
#  AUTHOR'S NOTE: this is a 'C-ret' and not "S-ret" because S-ret does not register
#   as a key
"C-ret" = ["move_line_up", "goto_line_end_newline"]
"ret" = ["move_line_down", "goto_first_nonwhitespace"]
"home" = "goto_first_nonwhitespace"  # this will help with code stuff.
"pageup" = ["page_cursor_up", "align_view_top"]  # duplicate in NOR, INS, SEL
"pagedown" = ["page_cursor_down", "align_view_bottom"]  # duplicate in NOR, INS, SEL
"C-L" = ":toggle-option soft-wrap.enable"

# selection options (or, lack thereof)
"esc" = "collapse_selection"
"x" = "select_line_below"
"X" = "select_line_above"
"C-/" = ["toggle_comments", "move_line_down", "goto_line_start"]
"w" = ["move_next_word_start", "collapse_selection"]
"W" = "move_next_word_start"
"e" = ["move_next_word_end", "collapse_selection"]
"E" = "move_next_word_end"
"b" = ["move_prev_word_start", "collapse_selection"]
"B" = "move_prev_word_start"
"d" = "delete_selection_noyank"
"D" = "delete_char_backward"
"c" = "copy_selection_on_next_line"  # dupe cursor down (formerly 'C')
"C" = "copy_selection_on_prev_line"  # dupe cursor up (formerly 'Alt-C')

# yank actions
"y" = "yank_to_clipboard"
"C-x" = ["yank_to_clipboard", "delete_selection"] # 'cut'
# dupe line after
"C-d" = ["extend_to_line_bounds", "yank_to_clipboard", ":clipboard-paste-after"]
# dupe line before
"C-D" = [
  "extend_to_line_bounds",
  "yank_to_clipboard",
  ":clipboard-paste-before",
]
# paste actions
"p" = ":clipboard-paste-after"
"P" = ":clipboard-paste-before"

# alternative to this is (S-)U, however we might hit these
#  two shortcuts intuitively as well
"C-y" = "redo"
"C-z" = "undo"
"C-l" = ":fmt"
"C-s" = ":w"

# indent / unindent
"tab" = "indent"
"S-tab" = "unindent"

# moving around buffers
"C-pageup" = "goto_previous_buffer"
"C-pagedown" = "goto_next_buffer"
"C-t" = ":new"
"C-w" = ":buffer-close"
"C-o" = "file_picker"
"C-O" = "buffer_picker"

# unbind the following commands
#  these are annoying to mistype
"a" = "no_op"
"o" = "no_op"

## these could be destructive if hit by accident
"Y" = "no_op"
"C-Y" = "no_op"
"C-Z" = "no_op"

[keys.insert]
"C-space" = "completion"
"backspace" = "delete_char_backward"
"C-backspace" = "delete_word_backward"
"del" = "delete_char_forward"
"C-del" = "delete_word_forward"
"home" = "goto_first_nonwhitespace"  # this will help with code stuff.
"pageup" = ["page_cursor_up", "align_view_top"]  # duplicate in NOR, INS, SEL
"pagedown" = ["page_cursor_down", "align_view_bottom"]  # duplicate in NOR, INS, SEL

[keys.select]
"y" = "yank_to_clipboard"
"home" = "goto_first_nonwhitespace"  # this will help with code stuff.
"pageup" = ["page_cursor_up", "align_view_top"]  # duplicate in NOR, INS, SEL
"pagedown" = ["page_cursor_down", "align_view_bottom"]  # duplicate in NOR, INS, SEL
