theme = "jetbrains_dark"

[editor]
mouse = true
bufferline = "always"
cursorline = true
cursorcolumn = true
rulers = [80, 120]
true-color = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# https://docs.helix-editor.com/master/configuration.html#editorsoft-wrap-section
[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.whitespace.render]
nbsp="all"
nnbsp="all"
tab="all"

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-modification-indicator", "version-control", "file-name"]
right = [ "position", "position-percentage", "total-line-numbers", "file-encoding", "file-line-ending" ]

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true
display-messages = true

[editor.file-picker]
hidden = false

[editor.search]
smart-case = true
wrap-around = true

[editor.smart-tab]
enable = false

[keys.normal]
"C-pageup" = "goto_previous_buffer"
"C-pagedown" = "goto_next_buffer"
"C-w" = "wclose"
"C-o" = "file_picker"
"C-S-o" = "buffer_picker"
"C-/" = "toggle_comments"
"d" = "delete_selection_noyank"
"C-d" = ["yank_to_clipboard", ":clipboard-paste-after"]
"C-D" = ["yank_to_clipboard", ":clipboard-paste-before"]
"C-x" = ["yank_to_clipboard", "delete_selection"]
"p" = ":clipboard-paste-after"
"P" = ":clipboard-paste-before"
"y" = "yank_to_clipboard"
"C-Z" = "redo"
"C-y" = "redo"
"C-z" = "undo"
"C-l" = ":fmt"
"C-t" = ":new"
"tab" = "indent"
"S-tab" = "unindent"
"x" = "select_line_below"
"X" = "select_line_above"

# unbind the following commands
"a" = "no_op"
"o" = "no_op"

[keys.insert]
C-backspace = "delete_word_backward"
